import asyncio
import json
import os
import logging
from typing import Optional

import nats
from groq import Groq
from pydantic import BaseModel
from opentelemetry import trace
from opentelemetry.trace import Status, StatusCode

# Настройка логирования
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Конфигурация
NATS_URL = os.getenv("NATS_URL", "nats://nats:4222")
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
LLM_MODEL = os.getenv("LLM_MODEL", "llama3-8b-8192")
SUBJECT_REQUEST = "llm.task"
SUBJECT_RESPONSE = "llm.result"

# Инициализация клиента Groq
groq_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None

# Модели данных
class LLMTask(BaseModel):
    task_id: str
    task_type: str  # "analyze_code", "generate_docs", "suggest_tests"
    code: Optional[str] = None
    language: Optional[str] = "go"
    context: Optional[dict] = None

class LLMResult(BaseModel):
    task_id: str
    result: str
    reasoning: Optional[str] = None
    error: Optional[str] = None

async def process_llm_task(task: LLMTask) -> LLMResult:
    """Обработка задачи с использованием LLM."""
    tracer = trace.get_tracer(__name__)
    with tracer.start_as_current_span("llm.process") as span:
        span.set_attributes({
            "task.id": task.task_id,
            "task.type": task.task_type,
            "language": task.language,
        })

        if not groq_client:
            span.set_status(Status(StatusCode.ERROR, "Groq API key not configured"))
            return LLMResult(
                task_id=task.task_id,
                result="",
                error="Groq API key not configured"
            )

        try:
            prompt = build_prompt(task)
            logger.info(f"Processing LLM task {task.task_id} with model {LLM_MODEL}")

            response = groq_client.chat.completions.create(
                model=LLM_MODEL,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.7,
                max_tokens=1024,
            )

            result_text = response.choices[0].message.content
            logger.info(f"LLM response received for task {task.task_id}")

            span.set_status(Status(StatusCode.OK))
            return LLMResult(
                task_id=task.task_id,
                result=result_text,
                reasoning="Generated by Groq LLM",
            )
        except Exception as e:
            logger.error(f"LLM processing failed: {e}")
            span.record_exception(e)
            span.set_status(Status(StatusCode.ERROR, str(e)))
            return LLMResult(
                task_id=task.task_id,
                result="",
                error=str(e)
            )

def build_prompt(task: LLMTask) -> str:
    """Создание промпта в зависимости от типа задачи."""
    base_prompt = f"You are an expert software testing assistant. Task type: {task.task_type}. Language: {task.language}.\n"
    if task.code:
        base_prompt += f"Code snippet:\n```{task.language}\n{task.code}\n```\n"
    if task.context:
        base_prompt += f"Additional context: {json.dumps(task.context)}\n"

    if task.task_type == "analyze_code":
        base_prompt += "Analyze the code for potential bugs, code smells, and suggest improvements. Provide concise analysis."
    elif task.task_type == "generate_docs":
        base_prompt += "Generate documentation for the code (function descriptions, usage examples)."
    elif task.task_type == "suggest_tests":
        base_prompt += "Suggest unit test cases for the code. Include test scenarios and edge cases."
    else:
        base_prompt += "Provide helpful insights about the code."

    base_prompt += "\nRespond in plain text, no markdown."
    return base_prompt

async def message_handler(msg):
    """Обработчик входящих сообщений NATS."""
    logger.info(f"Received message on {msg.subject}")
    try:
        data = json.loads(msg.data.decode())
        task = LLMTask(**data)
        logger.info(f"Processing task {task.task_id}")

        result = await process_llm_task(task)

        # Отправка ответа
        response_data = result.dict()
        await msg.respond(json.dumps(response_data).encode())
        logger.info(f"Response sent for task {task.task_id}")
    except Exception as e:
        logger.error(f"Error processing message: {e}")
        error_result = LLMResult(
            task_id="unknown",
            result="",
            error=str(e)
        )
        await msg.respond(json.dumps(error_result.dict()).encode())

async def main():
    """Основная функция запуска агента."""
    logger.info("Starting Python LLM Agent...")

    if not GROQ_API_KEY:
        logger.warning("GROQ_API_KEY not set. LLM functionality will be limited.")

    # Подключение к NATS
    try:
        nc = await nats.connect(NATS_URL)
        logger.info(f"Connected to NATS at {NATS_URL}")
    except Exception as e:
        logger.error(f"Failed to connect to NATS: {e}")
        return

    # Подписка на топик
    sub = await nc.subscribe(SUBJECT_REQUEST, cb=message_handler)
    logger.info(f"Subscribed to {SUBJECT_REQUEST}")

    # Бесконечное ожидание
    await asyncio.Future()

    # Закрытие подключения (недостижимо в текущей реализации)
    await sub.unsubscribe()
    await nc.close()

if __name__ == "__main__":
    asyncio.run(main())